version: '3.8'
services:
  client:
    build:
      context: ./blog-admin/
      dockerfile: .Dockerfile
    ports:
      - "3000:3000" # Assuming the client runs on port 3000

  server:
    build:
      context: ./blog-server/
      dockerfile: .Dockerfile
    ports:
      - "5000:5000" # Assuming the server runs on port 5000